-- 623 — Contratos entre unidades, com assinatura eletrônica simples.
--
-- As filiais fazem negócio com a Matriz e entre si (serviço prestado, cessão
-- de espaço, fornecimento, mútuo), e o acordo não existia no sistema: o valor
-- aparecia no financeiro sem o papel que o justifica. Documentos (476/528) não
-- serve, porque lá quem publica fala e quem recebe lê. Contrato é acordo entre
-- DUAS PARTES, e cada uma precisa aceitar.
--
-- ─── QUEM REPRESENTA CADA PARTE ─────────────────────────────────────────────
--
-- Parte é uma unidade: 'Matriz', 'SuperMax', 'MaxLook' ou 'TechMax'.
--   • Filial: o GERENTE dela. Ele cria, envia, assina, recusa, encerra.
--   • Matriz: o ADMIN (o professor), `role = 'admin'` LITERAL. A Matriz não
--     tem gerente, e `auth_is_admin()` incluiria CEO e conselheiro, que são
--     alunos (vide feedback_auth_is_admin_inclui_alunos).
-- CEO e conselheiro LEEM todos os contratos (menos rascunho alheio); não
-- assinam. Colaborador não vê contrato nenhum: é papel de gestão.
--
-- ─── O CICLO ────────────────────────────────────────────────────────────────
--
--   rascunho ──(A assina)──▶ aguardando ──(B assina)──▶ vigente ──▶ encerrado
--                                │                         └──────▶ rescindido
--                                └──(qualquer parte)──▶ recusado
--
-- Rascunho só a parte A enxerga (e o admin). Assinar é o que envia: ninguém
-- manda para o outro lado um contrato que ele mesmo não aceitou.
-- A troca de status acontece SÓ pelas RPCs; a RLS de UPDATE só deixa mexer em
-- rascunho, então nenhum cliente escreve 'vigente' na mão.
--
-- ─── A ASSINATURA ───────────────────────────────────────────────────────────
--
-- Lei 14.063/2020, art. 4º: simples, avançada e qualificada. Esta é a SIMPLES:
-- identifica quem assinou (sessão autenticada), grava a hora pelo relógio do
-- banco e amarra a assinatura ao arquivo por um SHA-256. O resumo é calculado
-- no navegador de quem sobe; quem assina manda o resumo que ELE conferiu, e a
-- RPC recusa se não bater com o guardado. Depois da primeira assinatura o
-- arquivo não se troca mais (a RLS só edita rascunho), então as duas
-- assinaturas valem sobre os mesmos bytes. Mudar o contrato é um ADITIVO:
-- contrato novo apontando para o de origem, assinaturas do zero.
-- Avançada e qualificada exigem certificado ICP-Brasil ou serviço pago — o
-- manifesto impresso diz isso, para o aluno não sair achando que é a mesma
-- coisa.
--
-- ─── RLS ────────────────────────────────────────────────────────────────────
--
-- Tudo escrito com `(SELECT auth_x())`, o padrão das migr. 597-599: helper
-- crua na policy roda por linha (incidente de 15/09).
--
-- IDEMPOTENTE. APLICAR NOS 4 PROJETOS.

BEGIN;

-- ────────────────────────────────────────────────────────────────────────────
-- 1. Tabelas
-- ────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.contratos (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Número humano ("CT-0007"), o que se cita na conversa e no manifesto.
  numero              bigint GENERATED BY DEFAULT AS IDENTITY,
  titulo              text NOT NULL CHECK (length(btrim(titulo)) > 0),
  objeto              text,
  parte_a             text NOT NULL CHECK (parte_a IN ('Matriz', 'SuperMax', 'MaxLook', 'TechMax')),
  parte_b             text NOT NULL CHECK (parte_b IN ('Matriz', 'SuperMax', 'MaxLook', 'TechMax')),
  valor               numeric(14,2) CHECK (valor IS NULL OR valor >= 0),
  condicoes           text,
  vigencia_inicio     date,
  vigencia_fim        date,
  arquivo_path        text NOT NULL,
  arquivo_nome        text NOT NULL,
  arquivo_mime        text,
  arquivo_tamanho     bigint,
  arquivo_sha256      text NOT NULL CHECK (arquivo_sha256 ~ '^[0-9a-f]{64}$'),
  status              text NOT NULL DEFAULT 'rascunho'
                        CHECK (status IN ('rascunho', 'aguardando', 'vigente', 'recusado', 'encerrado', 'rescindido')),
  -- Aditivo: o contrato que este altera. O original continua como estava.
  contrato_pai_id     uuid REFERENCES public.contratos(id) ON DELETE SET NULL,
  criado_por          uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  criado_por_nome     text,
  enviado_em          timestamptz,
  vigente_desde       timestamptz,
  encerrado_em        timestamptz,
  encerrado_por_nome  text,
  motivo_encerramento text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT contratos_partes_distintas CHECK (parte_a <> parte_b),
  CONSTRAINT contratos_vigencia_ordem CHECK (
    vigencia_inicio IS NULL OR vigencia_fim IS NULL OR vigencia_fim >= vigencia_inicio)
);

COMMENT ON TABLE public.contratos IS
  'Migr. 623 — contrato entre duas unidades. Parte A cria e assina primeiro; vigente com as duas assinaturas. Status só muda por RPC.';
COMMENT ON COLUMN public.contratos.arquivo_sha256 IS
  'Resumo SHA-256 (hex minúsculo) do arquivo, calculado no navegador de quem subiu. Toda assinatura é conferida contra ele.';

CREATE INDEX IF NOT EXISTS contratos_partes_idx ON public.contratos (parte_a, parte_b, status);
CREATE INDEX IF NOT EXISTS contratos_pai_idx    ON public.contratos (contrato_pai_id) WHERE contrato_pai_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.contratos_assinaturas (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  contrato_id     uuid NOT NULL REFERENCES public.contratos(id) ON DELETE CASCADE,
  parte           text NOT NULL CHECK (parte IN ('Matriz', 'SuperMax', 'MaxLook', 'TechMax')),
  user_id         uuid REFERENCES public.user_profiles(id) ON DELETE SET NULL,
  -- Carimbos do momento: um ano depois o manifesto continua dizendo quem era
  -- e em que cargo, mesmo que a pessoa tenha saído ou mudado de unidade.
  nome_snapshot   text NOT NULL,
  cargo_snapshot  text NOT NULL,
  arquivo_sha256  text NOT NULL,
  assinado_em     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (contrato_id, parte)
);

COMMENT ON TABLE public.contratos_assinaturas IS
  'Migr. 623 — uma assinatura por parte. Só a RPC assinar_contrato grava (sem policy de escrita).';

ALTER TABLE public.contratos             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contratos_assinaturas ENABLE ROW LEVEL SECURITY;

-- ────────────────────────────────────────────────────────────────────────────
-- 2. RLS de `contratos`
-- ────────────────────────────────────────────────────────────────────────────

DROP POLICY IF EXISTS contratos_select ON public.contratos;
CREATE POLICY contratos_select ON public.contratos
  FOR SELECT TO authenticated
  USING (
    (SELECT auth_user_role()) = 'admin'
    OR ((SELECT auth_user_role()) IN ('ceo', 'conselheiro') AND status <> 'rascunho')
    OR ((SELECT auth_user_role()) = 'gerente' AND (
          (SELECT auth_user_filial()) = parte_a
          OR ((SELECT auth_user_filial()) = parte_b AND status <> 'rascunho')))
  );

-- Cria quem representa a parte A, sempre como rascunho e em nome próprio.
DROP POLICY IF EXISTS contratos_insert ON public.contratos;
CREATE POLICY contratos_insert ON public.contratos
  FOR INSERT TO authenticated
  WITH CHECK (
    status = 'rascunho'
    AND criado_por = (SELECT auth.uid())
    AND (
      ((SELECT auth_user_role()) = 'admin' AND parte_a = 'Matriz')
      OR ((SELECT auth_user_role()) = 'gerente' AND parte_a <> 'Matriz'
          AND (SELECT auth_user_filial()) = parte_a)
    )
  );

-- Editar: só rascunho, só a parte A. O WITH CHECK repete o status, senão o
-- UPDATE escreveria 'vigente' por fora da RPC.
DROP POLICY IF EXISTS contratos_update ON public.contratos;
CREATE POLICY contratos_update ON public.contratos
  FOR UPDATE TO authenticated
  USING (
    status = 'rascunho'
    AND (
      ((SELECT auth_user_role()) = 'admin' AND parte_a = 'Matriz')
      OR ((SELECT auth_user_role()) = 'gerente' AND parte_a <> 'Matriz'
          AND (SELECT auth_user_filial()) = parte_a)
    )
  )
  WITH CHECK (
    status = 'rascunho'
    AND (
      ((SELECT auth_user_role()) = 'admin' AND parte_a = 'Matriz')
      OR ((SELECT auth_user_role()) = 'gerente' AND parte_a <> 'Matriz'
          AND (SELECT auth_user_filial()) = parte_a)
    )
  );

-- Excluir: a parte A o próprio rascunho; o professor qualquer um (limpeza de
-- turma). Contrato assinado não some pela mão do aluno.
DROP POLICY IF EXISTS contratos_delete ON public.contratos;
CREATE POLICY contratos_delete ON public.contratos
  FOR DELETE TO authenticated
  USING (
    (SELECT auth_user_role()) = 'admin'
    OR (status = 'rascunho'
        AND (SELECT auth_user_role()) = 'gerente' AND parte_a <> 'Matriz'
        AND (SELECT auth_user_filial()) = parte_a)
  );

-- Assinaturas: vê quem vê o contrato. A subconsulta passa pela RLS de
-- `contratos`, então a régua é uma só.
DROP POLICY IF EXISTS contratos_assinaturas_select ON public.contratos_assinaturas;
CREATE POLICY contratos_assinaturas_select ON public.contratos_assinaturas
  FOR SELECT TO authenticated
  USING (EXISTS (SELECT 1 FROM public.contratos c WHERE c.id = contrato_id));

-- ────────────────────────────────────────────────────────────────────────────
-- 3. Quem representa a parte — para as RPCs (policy escreve inline)
-- ────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.contrato_representa(p_parte text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT COALESCE((
    SELECT (p.role = 'admin' AND p_parte = 'Matriz')
        OR (p.role = 'gerente' AND p_parte <> 'Matriz' AND p.filial = p_parte)
      FROM public.user_profiles p
     WHERE p.id = auth.uid() AND p.desligado_em IS NULL
  ), false);
$function$;

COMMENT ON FUNCTION public.contrato_representa(text) IS
  'Migr. 623 — quem está logado assina por esta parte? Matriz = role admin literal; filial = o gerente dela. As policies de contratos repetem a régua inline (padrão 597/598).';

REVOKE ALL ON FUNCTION public.contrato_representa(text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.contrato_representa(text) TO authenticated, service_role;

-- ────────────────────────────────────────────────────────────────────────────
-- 4. Assinar
-- ────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.assinar_contrato(p_contrato_id uuid, p_sha256 text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_c      public.contratos;
  v_parte  text;
  v_nome   text;
  v_role   text;
  v_total  int;
  v_status text;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Não autenticado.' USING ERRCODE = '42501';
  END IF;

  SELECT * INTO v_c FROM public.contratos WHERE id = p_contrato_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Contrato não encontrado.' USING ERRCODE = 'P0002';
  END IF;

  IF public.contrato_representa(v_c.parte_a) THEN
    v_parte := v_c.parte_a;
  ELSIF public.contrato_representa(v_c.parte_b) AND v_c.status <> 'rascunho' THEN
    v_parte := v_c.parte_b;
  ELSE
    RAISE EXCEPTION 'Só o gerente de uma das partes (ou o professor, pela Matriz) assina este contrato.'
      USING ERRCODE = '42501';
  END IF;

  IF v_c.status NOT IN ('rascunho', 'aguardando') THEN
    RAISE EXCEPTION 'Este contrato está % e não recebe mais assinatura.', v_c.status
      USING ERRCODE = 'P0001';
  END IF;

  IF v_c.vigencia_fim IS NOT NULL
     AND v_c.vigencia_fim < (now() AT TIME ZONE 'America/Rio_Branco')::date THEN
    RAISE EXCEPTION 'A vigência deste contrato já terminou (%). Não se assina contrato vencido.',
      to_char(v_c.vigencia_fim, 'DD/MM/YYYY') USING ERRCODE = 'P0001';
  END IF;

  -- O resumo que quem assina conferiu tem de ser o do arquivo guardado. Se não
  -- bate, a pessoa está assinando outra coisa que não o contrato.
  IF lower(COALESCE(p_sha256, '')) <> v_c.arquivo_sha256 THEN
    RAISE EXCEPTION 'O arquivo conferido não é o do contrato (resumo SHA-256 diferente). Recarregue a tela e confira de novo.'
      USING ERRCODE = 'P0001';
  END IF;

  IF EXISTS (SELECT 1 FROM public.contratos_assinaturas
              WHERE contrato_id = v_c.id AND parte = v_parte) THEN
    RAISE EXCEPTION 'A % já assinou este contrato.', v_parte USING ERRCODE = 'P0001';
  END IF;

  SELECT nome, role INTO v_nome, v_role FROM public.user_profiles WHERE id = auth.uid();

  INSERT INTO public.contratos_assinaturas
    (contrato_id, parte, user_id, nome_snapshot, cargo_snapshot, arquivo_sha256)
  VALUES
    (v_c.id, v_parte, auth.uid(), COALESCE(v_nome, '—'),
     CASE v_role WHEN 'admin' THEN 'Administrador (Matriz)' ELSE 'Gerente' END,
     v_c.arquivo_sha256);

  SELECT count(*) INTO v_total FROM public.contratos_assinaturas WHERE contrato_id = v_c.id;

  IF v_total >= 2 THEN
    v_status := 'vigente';
    UPDATE public.contratos
       SET status = 'vigente', vigente_desde = now(), enviado_em = COALESCE(enviado_em, now())
     WHERE id = v_c.id;
  ELSE
    v_status := 'aguardando';
    UPDATE public.contratos
       SET status = 'aguardando', enviado_em = COALESCE(enviado_em, now())
     WHERE id = v_c.id;
  END IF;

  RETURN v_status;
END;
$function$;

REVOKE ALL ON FUNCTION public.assinar_contrato(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.assinar_contrato(uuid, text) TO authenticated, service_role;

-- ────────────────────────────────────────────────────────────────────────────
-- 5. Recusar (parte B) ou retirar (parte A) — só enquanto aguarda
-- ────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.recusar_contrato(p_contrato_id uuid, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_c    public.contratos;
  v_nome text;
BEGIN
  SELECT * INTO v_c FROM public.contratos WHERE id = p_contrato_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Contrato não encontrado.' USING ERRCODE = 'P0002';
  END IF;

  IF NOT (public.contrato_representa(v_c.parte_a) OR public.contrato_representa(v_c.parte_b)) THEN
    RAISE EXCEPTION 'Só quem representa uma das partes recusa o contrato.' USING ERRCODE = '42501';
  END IF;

  IF v_c.status <> 'aguardando' THEN
    RAISE EXCEPTION 'Só se recusa contrato que está aguardando assinatura.' USING ERRCODE = 'P0001';
  END IF;

  IF length(btrim(COALESCE(p_motivo, ''))) < 5 THEN
    RAISE EXCEPTION 'Diga o motivo da recusa — é o que a outra parte vai ler.' USING ERRCODE = 'P0001';
  END IF;

  SELECT nome INTO v_nome FROM public.user_profiles WHERE id = auth.uid();

  UPDATE public.contratos
     SET status = 'recusado', encerrado_em = now(),
         encerrado_por_nome = v_nome, motivo_encerramento = btrim(p_motivo)
   WHERE id = v_c.id;
END;
$function$;

REVOKE ALL ON FUNCTION public.recusar_contrato(uuid, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.recusar_contrato(uuid, text) TO authenticated, service_role;

-- ────────────────────────────────────────────────────────────────────────────
-- 6. Encerrar (fim combinado) ou rescindir (rompimento) — só vigente
-- ────────────────────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.encerrar_contrato(p_contrato_id uuid, p_rescisao boolean, p_motivo text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_c    public.contratos;
  v_nome text;
BEGIN
  SELECT * INTO v_c FROM public.contratos WHERE id = p_contrato_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Contrato não encontrado.' USING ERRCODE = 'P0002';
  END IF;

  IF NOT (public.contrato_representa(v_c.parte_a) OR public.contrato_representa(v_c.parte_b)) THEN
    RAISE EXCEPTION 'Só quem representa uma das partes encerra o contrato.' USING ERRCODE = '42501';
  END IF;

  IF v_c.status <> 'vigente' THEN
    RAISE EXCEPTION 'Só se encerra contrato vigente.' USING ERRCODE = 'P0001';
  END IF;

  IF COALESCE(p_rescisao, false) AND length(btrim(COALESCE(p_motivo, ''))) < 5 THEN
    RAISE EXCEPTION 'Rescisão pede motivo.' USING ERRCODE = 'P0001';
  END IF;

  SELECT nome INTO v_nome FROM public.user_profiles WHERE id = auth.uid();

  UPDATE public.contratos
     SET status = CASE WHEN COALESCE(p_rescisao, false) THEN 'rescindido' ELSE 'encerrado' END,
         encerrado_em = now(), encerrado_por_nome = v_nome,
         motivo_encerramento = NULLIF(btrim(COALESCE(p_motivo, '')), '')
   WHERE id = v_c.id;
END;
$function$;

REVOKE ALL ON FUNCTION public.encerrar_contrato(uuid, boolean, text) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.encerrar_contrato(uuid, boolean, text) TO authenticated, service_role;

-- ────────────────────────────────────────────────────────────────────────────
-- 7. Bucket privado
-- ────────────────────────────────────────────────────────────────────────────

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'contratos', 'contratos', false, 10485760,
  ARRAY[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/msword'
  ]
)
ON CONFLICT (id) DO UPDATE
  SET public             = EXCLUDED.public,
      file_size_limit    = EXCLUDED.file_size_limit,
      allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS contratos_bucket_read   ON storage.objects;
DROP POLICY IF EXISTS contratos_bucket_insert ON storage.objects;
DROP POLICY IF EXISTS contratos_bucket_delete ON storage.objects;

-- Ler o objeto = enxergar um contrato que aponta para ele. A subconsulta passa
-- pela RLS de `contratos`: caminho adivinhado não entrega o contrato alheio.
CREATE POLICY contratos_bucket_read ON storage.objects
  FOR SELECT TO authenticated
  USING (
    bucket_id = 'contratos'
    AND EXISTS (SELECT 1 FROM public.contratos c WHERE c.arquivo_path = storage.objects.name)
  );

-- Subir: quem pode representar alguma parte, na pasta do próprio uid (a pasta
-- é o que a policy confere — vide feedback_upload_pasta_do_bucket_e_de_quem_sobe).
CREATE POLICY contratos_bucket_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'contratos'
    AND (storage.foldername(name))[1] = ((SELECT auth.uid()))::text
    AND (SELECT auth_user_role()) IN ('admin', 'gerente')
  );

-- Apagar: o dono do objeto, ou o professor — e nunca o arquivo de um contrato
-- que já saiu do rascunho. É esse arquivo que as assinaturas atestam.
CREATE POLICY contratos_bucket_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'contratos'
    AND (owner = (SELECT auth.uid()) OR (SELECT auth_user_role()) = 'admin')
    AND NOT EXISTS (
      SELECT 1 FROM public.contratos c
       WHERE c.arquivo_path = storage.objects.name AND c.status <> 'rascunho'
    )
  );

-- ────────────────────────────────────────────────────────────────────────────
-- 8. Trava do desligado nas tabelas novas (migr. 308)
-- ────────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  t      text;
  v_cmd  text;
  v_nome text;
BEGIN
  FOREACH t IN ARRAY ARRAY['contratos', 'contratos_assinaturas'] LOOP
    FOREACH v_cmd IN ARRAY ARRAY['INSERT', 'UPDATE', 'DELETE'] LOOP
      v_nome := 'zz_desligado_bloqueia_' || lower(v_cmd);
      EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', v_nome, t);
      IF v_cmd = 'INSERT' THEN
        EXECUTE format(
          'CREATE POLICY %I ON public.%I AS RESTRICTIVE FOR INSERT TO authenticated
             WITH CHECK (NOT (SELECT auth_desligado()))', v_nome, t);
      ELSE
        EXECUTE format(
          'CREATE POLICY %I ON public.%I AS RESTRICTIVE FOR %s TO authenticated
             USING (NOT (SELECT auth_desligado()))', v_nome, t, v_cmd);
      END IF;
    END LOOP;
  END LOOP;
END $$;

-- ────────────────────────────────────────────────────────────────────────────
-- 9. Realtime — assinatura do outro lado aparece sem F5
-- ────────────────────────────────────────────────────────────────────────────

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['contratos', 'contratos_assinaturas'] LOOP
    IF NOT EXISTS (
      SELECT 1 FROM pg_publication_tables
       WHERE pubname = 'supabase_realtime' AND schemaname = 'public' AND tablename = t
    ) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I', t);
    END IF;
  END LOOP;
END $$;

COMMIT;

NOTIFY pgrst, 'reload schema';

-- ── Conferência ─────────────────────────────────────────────────────────────
--   SELECT policyname, cmd FROM pg_policies WHERE tablename LIKE 'contratos%';
--   SELECT has_function_privilege('anon', 'public.assinar_contrato(uuid,text)', 'EXECUTE'); -- false
