-- MIGR 630 — dois buracos da taxonomia padrão (migr. 629).
--
-- Achados ao reclassificar o catálogo semente (src/lib/catalogoNicho.ts):
--   * TechMax não tinha onde pôr câmera (digital, de ação, de segurança) —
--     foi esse buraco que levou a Contabilidade a criar "Foto e Video".
--     Entra "Câmeras e segurança", como o departamento da KaBuM.
--   * MaxLook não tinha onde pôr luva e cachecol de inverno. Entra
--     "Cachecóis, luvas e gorros" em Acessórios.
--
-- A lista inteira é regravada (a ordem das categorias da TechMax muda com a
-- nova) e aplicada nas três filiais — `aplicar_taxonomia_padrao` é
-- idempotente: adota o que existe e só cria o que falta.
--
-- O produto que a Contabilidade pôs em "Foto e Video" (uma câmera) vai para a
-- categoria nova. A categoria "Foto e Video" em si fica: foi criada pelo aluno
-- e é Própria.

DELETE FROM public.taxonomia_padrao;
INSERT INTO public.taxonomia_padrao (nicho, categoria, subcategoria, ordem, cor, icone) VALUES
  ('SuperMax', 'Mercearia', '', 1, '#f59e0b', '🥫'),
  ('SuperMax', 'Mercearia', 'Arroz', 1, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Feijão', 2, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Grãos e cereais', 3, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Farinhas e farofas', 4, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Massas', 5, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Molhos e extratos de tomate', 6, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Temperos e condimentos', 7, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Óleos, azeites e vinagres', 8, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Açúcar e adoçantes', 9, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Enlatados e conservas', 10, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Sopas e caldos', 11, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Ingredientes para bolos e sobremesas', 12, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Leite condensado e creme de leite', 13, NULL, NULL),
  ('SuperMax', 'Mercearia', 'Naturais e integrais', 14, NULL, NULL),
  ('SuperMax', 'Matinais', '', 2, '#f97316', '🍞'),
  ('SuperMax', 'Matinais', 'Café', 1, NULL, NULL),
  ('SuperMax', 'Matinais', 'Chás', 2, NULL, NULL),
  ('SuperMax', 'Matinais', 'Achocolatados e cappuccinos', 3, NULL, NULL),
  ('SuperMax', 'Matinais', 'Leite em pó', 4, NULL, NULL),
  ('SuperMax', 'Matinais', 'Cereais matinais e granolas', 5, NULL, NULL),
  ('SuperMax', 'Matinais', 'Biscoitos e bolachas', 6, NULL, NULL),
  ('SuperMax', 'Matinais', 'Torradas', 7, NULL, NULL),
  ('SuperMax', 'Matinais', 'Geleias, mel e cremes para pão', 8, NULL, NULL),
  ('SuperMax', 'Doces e snacks', '', 3, '#ec4899', '🍫'),
  ('SuperMax', 'Doces e snacks', 'Chocolates', 1, NULL, NULL),
  ('SuperMax', 'Doces e snacks', 'Balas, gomas e pirulitos', 2, NULL, NULL),
  ('SuperMax', 'Doces e snacks', 'Doces e sobremesas prontas', 3, NULL, NULL),
  ('SuperMax', 'Doces e snacks', 'Salgadinhos', 4, NULL, NULL),
  ('SuperMax', 'Doces e snacks', 'Amendoins e petiscos', 5, NULL, NULL),
  ('SuperMax', 'Bebidas', '', 4, '#06b6d4', '🥤'),
  ('SuperMax', 'Bebidas', 'Águas', 1, NULL, NULL),
  ('SuperMax', 'Bebidas', 'Refrigerantes', 2, NULL, NULL),
  ('SuperMax', 'Bebidas', 'Sucos e néctares', 3, NULL, NULL),
  ('SuperMax', 'Bebidas', 'Chás prontos', 4, NULL, NULL),
  ('SuperMax', 'Bebidas', 'Energéticos e isotônicos', 5, NULL, NULL),
  ('SuperMax', 'Bebidas', 'Bebidas vegetais', 6, NULL, NULL),
  ('SuperMax', 'Bebidas', 'Água de coco', 7, NULL, NULL),
  ('SuperMax', 'Bebidas', 'Gelo', 8, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', '', 5, '#8b5cf6', '🥤'),
  ('SuperMax', 'Bebidas alcoólicas', 'Cervejas', 1, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Vinhos', 2, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Espumantes', 3, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Cachaças', 4, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Vodcas', 5, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Uísques', 6, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Gins', 7, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Licores e aperitivos', 8, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Outros destilados', 9, NULL, NULL),
  ('SuperMax', 'Bebidas alcoólicas', 'Drinks prontos', 10, NULL, NULL),
  ('SuperMax', 'Açougue', '', 6, '#ef4444', '🥩'),
  ('SuperMax', 'Açougue', 'Carne bovina', 1, NULL, NULL),
  ('SuperMax', 'Açougue', 'Carne suína', 2, NULL, NULL),
  ('SuperMax', 'Açougue', 'Aves', 3, NULL, NULL),
  ('SuperMax', 'Açougue', 'Cordeiro e outras carnes', 4, NULL, NULL),
  ('SuperMax', 'Açougue', 'Linguiças frescas', 5, NULL, NULL),
  ('SuperMax', 'Açougue', 'Carnes temperadas e preparadas', 6, NULL, NULL),
  ('SuperMax', 'Peixaria', '', 7, '#3b82f6', '🧊'),
  ('SuperMax', 'Peixaria', 'Peixes', 1, NULL, NULL),
  ('SuperMax', 'Peixaria', 'Frutos do mar', 2, NULL, NULL),
  ('SuperMax', 'Peixaria', 'Bacalhau e pescados salgados', 3, NULL, NULL),
  ('SuperMax', 'Hortifruti', '', 8, '#22c55e', '🥦'),
  ('SuperMax', 'Hortifruti', 'Frutas', 1, NULL, NULL),
  ('SuperMax', 'Hortifruti', 'Legumes', 2, NULL, NULL),
  ('SuperMax', 'Hortifruti', 'Verduras', 3, NULL, NULL),
  ('SuperMax', 'Hortifruti', 'Temperos frescos', 4, NULL, NULL),
  ('SuperMax', 'Hortifruti', 'Cogumelos', 5, NULL, NULL),
  ('SuperMax', 'Hortifruti', 'Frutas secas e castanhas', 6, NULL, NULL),
  ('SuperMax', 'Hortifruti', 'Frutas e saladas cortadas', 7, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', '', 9, '#D4AF37', '🛒'),
  ('SuperMax', 'Frios e laticínios', 'Leites', 1, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Iogurtes e fermentados', 2, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Queijos', 3, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Requeijão e cream cheese', 4, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Manteigas e margarinas', 5, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Natas e chantilly', 6, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Ovos', 7, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Frios fatiados', 8, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Salsichas', 9, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Bacon e embutidos defumados', 10, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Patês e antepastos', 11, NULL, NULL),
  ('SuperMax', 'Frios e laticínios', 'Massas frescas', 12, NULL, NULL),
  ('SuperMax', 'Congelados', '', 10, '#06b6d4', '🧊'),
  ('SuperMax', 'Congelados', 'Hambúrgueres e empanados', 1, NULL, NULL),
  ('SuperMax', 'Congelados', 'Pratos prontos', 2, NULL, NULL),
  ('SuperMax', 'Congelados', 'Pizzas', 3, NULL, NULL),
  ('SuperMax', 'Congelados', 'Lasanhas e massas congeladas', 4, NULL, NULL),
  ('SuperMax', 'Congelados', 'Salgados e pães de queijo congelados', 5, NULL, NULL),
  ('SuperMax', 'Congelados', 'Vegetais congelados', 6, NULL, NULL),
  ('SuperMax', 'Congelados', 'Polpas de fruta', 7, NULL, NULL),
  ('SuperMax', 'Congelados', 'Sorvetes e açaí', 8, NULL, NULL),
  ('SuperMax', 'Congelados', 'Sobremesas congeladas', 9, NULL, NULL),
  ('SuperMax', 'Padaria e confeitaria', '', 11, '#D4AF37', '🍞'),
  ('SuperMax', 'Padaria e confeitaria', 'Pães da casa', 1, NULL, NULL),
  ('SuperMax', 'Padaria e confeitaria', 'Pães industrializados', 2, NULL, NULL),
  ('SuperMax', 'Padaria e confeitaria', 'Bolos', 3, NULL, NULL),
  ('SuperMax', 'Padaria e confeitaria', 'Doces e tortas de confeitaria', 4, NULL, NULL),
  ('SuperMax', 'Padaria e confeitaria', 'Salgados', 5, NULL, NULL),
  ('SuperMax', 'Padaria e confeitaria', 'Panetones e sazonais', 6, NULL, NULL),
  ('SuperMax', 'Rotisseria', '', 12, '#f97316', '🥩'),
  ('SuperMax', 'Rotisseria', 'Pratos quentes', 1, NULL, NULL),
  ('SuperMax', 'Rotisseria', 'Assados', 2, NULL, NULL),
  ('SuperMax', 'Rotisseria', 'Saladas e acompanhamentos', 3, NULL, NULL),
  ('SuperMax', 'Rotisseria', 'Marmitas e refeições completas', 4, NULL, NULL),
  ('SuperMax', 'Limpeza', '', 13, '#3b82f6', '🧼'),
  ('SuperMax', 'Limpeza', 'Sabão para roupas', 1, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Amaciantes', 2, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Alvejantes e tira-manchas', 3, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Detergentes', 4, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Desinfetantes e água sanitária', 5, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Limpadores multiuso', 6, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Limpeza de banheiro', 7, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Limpeza de cozinha', 8, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Limpa-vidros e lustra-móveis', 9, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Álcool', 10, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Inseticidas', 11, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Vassouras, rodos e baldes', 12, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Esponjas e palhas de aço', 13, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Panos e flanelas', 14, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Luvas', 15, NULL, NULL),
  ('SuperMax', 'Limpeza', 'Sacos de lixo e lixeiras', 16, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', '', 14, '#ec4899', '🧴'),
  ('SuperMax', 'Higiene e beleza', 'Shampoos', 1, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Condicionadores', 2, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Cremes e finalizadores', 3, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Colorações', 4, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Sabonetes', 5, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Desodorantes', 6, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Hidratantes', 7, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Protetor solar', 8, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Repelentes', 9, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Perfumes', 10, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Maquiagem', 11, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Unhas', 12, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Barbear e depilação', 13, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Creme dental', 14, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Escovas e fio dental', 15, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Enxaguantes bucais', 16, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Absorventes', 17, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Papel higiênico', 18, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Lenços de papel', 19, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Algodão e hastes', 20, NULL, NULL),
  ('SuperMax', 'Higiene e beleza', 'Primeiros socorros', 21, NULL, NULL),
  ('SuperMax', 'Bebê', '', 15, '#8b5cf6', '🎁'),
  ('SuperMax', 'Bebê', 'Fraldas', 1, NULL, NULL),
  ('SuperMax', 'Bebê', 'Lenços umedecidos', 2, NULL, NULL),
  ('SuperMax', 'Bebê', 'Higiene infantil', 3, NULL, NULL),
  ('SuperMax', 'Bebê', 'Papinhas e cereais infantis', 4, NULL, NULL),
  ('SuperMax', 'Bebê', 'Fórmulas infantis', 5, NULL, NULL),
  ('SuperMax', 'Pet', '', 16, '#f97316', '🐾'),
  ('SuperMax', 'Pet', 'Ração para cães', 1, NULL, NULL),
  ('SuperMax', 'Pet', 'Ração para gatos', 2, NULL, NULL),
  ('SuperMax', 'Pet', 'Ração para outros animais', 3, NULL, NULL),
  ('SuperMax', 'Pet', 'Petiscos', 4, NULL, NULL),
  ('SuperMax', 'Pet', 'Higiene e areia', 5, NULL, NULL),
  ('SuperMax', 'Pet', 'Acessórios e brinquedos', 6, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', '', 17, '#6b7280', '🏠'),
  ('SuperMax', 'Bazar e utilidades', 'Utensílios de cozinha', 1, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Descartáveis', 2, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Papel-toalha, guardanapos e alumínio', 3, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Organização', 4, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Churrasco', 5, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Camping, praia e piscina', 6, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Ferramentas', 7, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Automotivo', 8, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Pilhas e lâmpadas', 9, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Papelaria', 10, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Brinquedos', 11, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Festas', 12, NULL, NULL),
  ('SuperMax', 'Bazar e utilidades', 'Velas e fósforos', 13, NULL, NULL),
  ('TechMax', 'Celulares e tablets', '', 1, '#3b82f6', '📱'),
  ('TechMax', 'Celulares e tablets', 'Smartphones', 1, NULL, NULL),
  ('TechMax', 'Celulares e tablets', 'Celulares básicos', 2, NULL, NULL),
  ('TechMax', 'Celulares e tablets', 'Tablets', 3, NULL, NULL),
  ('TechMax', 'Celulares e tablets', 'Smartwatches e smartbands', 4, NULL, NULL),
  ('TechMax', 'Acessórios para celular', '', 2, '#06b6d4', '🔌'),
  ('TechMax', 'Acessórios para celular', 'Capas', 1, NULL, NULL),
  ('TechMax', 'Acessórios para celular', 'Películas', 2, NULL, NULL),
  ('TechMax', 'Acessórios para celular', 'Carregadores', 3, NULL, NULL),
  ('TechMax', 'Acessórios para celular', 'Cabos e adaptadores USB', 4, NULL, NULL),
  ('TechMax', 'Acessórios para celular', 'Power banks', 5, NULL, NULL),
  ('TechMax', 'Acessórios para celular', 'Suportes', 6, NULL, NULL),
  ('TechMax', 'TV e vídeo', '', 3, '#8b5cf6', '🖥️'),
  ('TechMax', 'TV e vídeo', 'Smart TVs', 1, NULL, NULL),
  ('TechMax', 'TV e vídeo', 'Projetores', 2, NULL, NULL),
  ('TechMax', 'TV e vídeo', 'Aparelhos de streaming', 3, NULL, NULL),
  ('TechMax', 'TV e vídeo', 'Suportes para TV', 4, NULL, NULL),
  ('TechMax', 'TV e vídeo', 'Cabos HDMI e de vídeo', 5, NULL, NULL),
  ('TechMax', 'Áudio', '', 4, '#ec4899', '🎧'),
  ('TechMax', 'Áudio', 'Fones de ouvido', 1, NULL, NULL),
  ('TechMax', 'Áudio', 'Caixas de som', 2, NULL, NULL),
  ('TechMax', 'Áudio', 'Soundbars e home theater', 3, NULL, NULL),
  ('TechMax', 'Áudio', 'Microfones', 4, NULL, NULL),
  ('TechMax', 'Áudio', 'Cabos e adaptadores de áudio', 5, NULL, NULL),
  ('TechMax', 'Computadores', '', 5, '#3b82f6', '💻'),
  ('TechMax', 'Computadores', 'Notebooks', 1, NULL, NULL),
  ('TechMax', 'Computadores', 'Desktops e mini PCs', 2, NULL, NULL),
  ('TechMax', 'Computadores', 'Monitores', 3, NULL, NULL),
  ('TechMax', 'Computadores', 'Impressoras e scanners', 4, NULL, NULL),
  ('TechMax', 'Computadores', 'Cartuchos e toners', 5, NULL, NULL),
  ('TechMax', 'Hardware', '', 6, '#6b7280', '🔧'),
  ('TechMax', 'Hardware', 'Processadores', 1, NULL, NULL),
  ('TechMax', 'Hardware', 'Placas-mãe', 2, NULL, NULL),
  ('TechMax', 'Hardware', 'Placas de vídeo', 3, NULL, NULL),
  ('TechMax', 'Hardware', 'Memórias RAM', 4, NULL, NULL),
  ('TechMax', 'Hardware', 'SSDs e HDs', 5, NULL, NULL),
  ('TechMax', 'Hardware', 'Fontes', 6, NULL, NULL),
  ('TechMax', 'Hardware', 'Gabinetes', 7, NULL, NULL),
  ('TechMax', 'Hardware', 'Coolers e refrigeração', 8, NULL, NULL),
  ('TechMax', 'Periféricos', '', 7, '#22c55e', '🖥️'),
  ('TechMax', 'Periféricos', 'Teclados', 1, NULL, NULL),
  ('TechMax', 'Periféricos', 'Mouses', 2, NULL, NULL),
  ('TechMax', 'Periféricos', 'Kits teclado e mouse', 3, NULL, NULL),
  ('TechMax', 'Periféricos', 'Headsets', 4, NULL, NULL),
  ('TechMax', 'Periféricos', 'Webcams', 5, NULL, NULL),
  ('TechMax', 'Periféricos', 'Mousepads', 6, NULL, NULL),
  ('TechMax', 'Periféricos', 'Hubs e adaptadores', 7, NULL, NULL),
  ('TechMax', 'Armazenamento externo', '', 8, '#f59e0b', '📦'),
  ('TechMax', 'Armazenamento externo', 'HDs e SSDs externos', 1, NULL, NULL),
  ('TechMax', 'Armazenamento externo', 'Pendrives', 2, NULL, NULL),
  ('TechMax', 'Armazenamento externo', 'Cartões de memória', 3, NULL, NULL),
  ('TechMax', 'Câmeras e segurança', '', 9, '#6b7280', '📱'),
  ('TechMax', 'Câmeras e segurança', 'Câmeras digitais', 1, NULL, NULL),
  ('TechMax', 'Câmeras e segurança', 'Câmeras de ação', 2, NULL, NULL),
  ('TechMax', 'Câmeras e segurança', 'Câmeras de segurança', 3, NULL, NULL),
  ('TechMax', 'Games', '', 10, '#8b5cf6', '🎮'),
  ('TechMax', 'Games', 'Consoles', 1, NULL, NULL),
  ('TechMax', 'Games', 'Jogos', 2, NULL, NULL),
  ('TechMax', 'Games', 'Controles', 3, NULL, NULL),
  ('TechMax', 'Games', 'Acessórios para consoles', 4, NULL, NULL),
  ('TechMax', 'Games', 'Cartões e gift cards', 5, NULL, NULL),
  ('TechMax', 'Games', 'Cadeiras e mesas gamer', 6, NULL, NULL),
  ('TechMax', 'Redes', '', 11, '#06b6d4', '🔌'),
  ('TechMax', 'Redes', 'Roteadores', 1, NULL, NULL),
  ('TechMax', 'Redes', 'Repetidores e mesh', 2, NULL, NULL),
  ('TechMax', 'Redes', 'Switches', 3, NULL, NULL),
  ('TechMax', 'Redes', 'Adaptadores Wi-Fi e Bluetooth', 4, NULL, NULL),
  ('TechMax', 'Redes', 'Cabos e conectores de rede', 5, NULL, NULL),
  ('TechMax', 'Redes', 'Modems', 6, NULL, NULL),
  ('TechMax', 'Energia', '', 12, '#f59e0b', '🔋'),
  ('TechMax', 'Energia', 'Nobreaks', 1, NULL, NULL),
  ('TechMax', 'Energia', 'Estabilizadores', 2, NULL, NULL),
  ('TechMax', 'Energia', 'Filtros de linha', 3, NULL, NULL),
  ('TechMax', 'Energia', 'Pilhas e baterias', 4, NULL, NULL),
  ('TechMax', 'Energia', 'Fontes e carregadores universais', 5, NULL, NULL),
  ('TechMax', 'Peças para assistência', '', 13, '#ef4444', '🔧'),
  ('TechMax', 'Peças para assistência', 'Telas e displays', 1, NULL, NULL),
  ('TechMax', 'Peças para assistência', 'Baterias', 2, NULL, NULL),
  ('TechMax', 'Peças para assistência', 'Conectores de carga', 3, NULL, NULL),
  ('TechMax', 'Peças para assistência', 'Cabos flex', 4, NULL, NULL),
  ('TechMax', 'Peças para assistência', 'Câmeras', 5, NULL, NULL),
  ('TechMax', 'Peças para assistência', 'Alto-falantes e microfones', 6, NULL, NULL),
  ('TechMax', 'Peças para assistência', 'Carcaças e tampas', 7, NULL, NULL),
  ('TechMax', 'Peças para assistência', 'Placas e componentes', 8, NULL, NULL),
  ('TechMax', 'Ferramentas e insumos de reparo', '', 14, '#f97316', '🔧'),
  ('TechMax', 'Ferramentas e insumos de reparo', 'Ferramentas', 1, NULL, NULL),
  ('TechMax', 'Ferramentas e insumos de reparo', 'Pasta térmica', 2, NULL, NULL),
  ('TechMax', 'Ferramentas e insumos de reparo', 'Adesivos e colas', 3, NULL, NULL),
  ('TechMax', 'Ferramentas e insumos de reparo', 'Solda e insumos', 4, NULL, NULL),
  ('MaxLook', 'Roupas', '', 1, '#D4AF37', '👕'),
  ('MaxLook', 'Roupas', 'Camisetas', 1, NULL, NULL),
  ('MaxLook', 'Roupas', 'Regatas', 2, NULL, NULL),
  ('MaxLook', 'Roupas', 'Blusas', 3, NULL, NULL),
  ('MaxLook', 'Roupas', 'Camisas', 4, NULL, NULL),
  ('MaxLook', 'Roupas', 'Polos', 5, NULL, NULL),
  ('MaxLook', 'Roupas', 'Moletons e suéteres', 6, NULL, NULL),
  ('MaxLook', 'Roupas', 'Casacos e jaquetas', 7, NULL, NULL),
  ('MaxLook', 'Roupas', 'Blazers e alfaiataria', 8, NULL, NULL),
  ('MaxLook', 'Roupas', 'Calças', 9, NULL, NULL),
  ('MaxLook', 'Roupas', 'Bermudas e shorts', 10, NULL, NULL),
  ('MaxLook', 'Roupas', 'Saias', 11, NULL, NULL),
  ('MaxLook', 'Roupas', 'Vestidos', 12, NULL, NULL),
  ('MaxLook', 'Roupas', 'Macacões', 13, NULL, NULL),
  ('MaxLook', 'Roupas', 'Conjuntos', 14, NULL, NULL),
  ('MaxLook', 'Moda íntima e pijamas', '', 2, '#ec4899', '👕'),
  ('MaxLook', 'Moda íntima e pijamas', 'Calcinhas', 1, NULL, NULL),
  ('MaxLook', 'Moda íntima e pijamas', 'Cuecas', 2, NULL, NULL),
  ('MaxLook', 'Moda íntima e pijamas', 'Sutiãs e tops', 3, NULL, NULL),
  ('MaxLook', 'Moda íntima e pijamas', 'Cintas e modeladores', 4, NULL, NULL),
  ('MaxLook', 'Moda íntima e pijamas', 'Meias', 5, NULL, NULL),
  ('MaxLook', 'Moda íntima e pijamas', 'Pijamas e camisolas', 6, NULL, NULL),
  ('MaxLook', 'Moda praia', '', 3, '#06b6d4', '🕶️'),
  ('MaxLook', 'Moda praia', 'Biquínis', 1, NULL, NULL),
  ('MaxLook', 'Moda praia', 'Maiôs', 2, NULL, NULL),
  ('MaxLook', 'Moda praia', 'Sungas', 3, NULL, NULL),
  ('MaxLook', 'Moda praia', 'Bermudas de praia', 4, NULL, NULL),
  ('MaxLook', 'Moda praia', 'Saídas de praia', 5, NULL, NULL),
  ('MaxLook', 'Moda esportiva', '', 4, '#22c55e', '👟'),
  ('MaxLook', 'Moda esportiva', 'Leggings', 1, NULL, NULL),
  ('MaxLook', 'Moda esportiva', 'Tops esportivos', 2, NULL, NULL),
  ('MaxLook', 'Moda esportiva', 'Camisetas e regatas esportivas', 3, NULL, NULL),
  ('MaxLook', 'Moda esportiva', 'Shorts e bermudas esportivos', 4, NULL, NULL),
  ('MaxLook', 'Moda esportiva', 'Calças e agasalhos esportivos', 5, NULL, NULL),
  ('MaxLook', 'Calçados', '', 5, '#f97316', '👟'),
  ('MaxLook', 'Calçados', 'Tênis', 1, NULL, NULL),
  ('MaxLook', 'Calçados', 'Sapatos', 2, NULL, NULL),
  ('MaxLook', 'Calçados', 'Sapatênis', 3, NULL, NULL),
  ('MaxLook', 'Calçados', 'Sapatilhas', 4, NULL, NULL),
  ('MaxLook', 'Calçados', 'Scarpins', 5, NULL, NULL),
  ('MaxLook', 'Calçados', 'Sandálias e rasteirinhas', 6, NULL, NULL),
  ('MaxLook', 'Calçados', 'Chinelos', 7, NULL, NULL),
  ('MaxLook', 'Calçados', 'Botas', 8, NULL, NULL),
  ('MaxLook', 'Calçados', 'Tamancos e mules', 9, NULL, NULL),
  ('MaxLook', 'Acessórios', '', 6, '#8b5cf6', '👜'),
  ('MaxLook', 'Acessórios', 'Bolsas', 1, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Mochilas', 2, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Carteiras', 3, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Cintos', 4, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Bonés e chapéus', 5, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Óculos', 6, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Relógios', 7, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Bijuterias', 8, NULL, NULL),
  ('MaxLook', 'Acessórios', 'Cachecóis, luvas e gorros', 9, NULL, NULL);

DO $m$
BEGIN
  PERFORM public.aplicar_taxonomia_padrao('SuperMax');
  PERFORM public.aplicar_taxonomia_padrao('MaxLook');
  PERFORM public.aplicar_taxonomia_padrao('TechMax');

  UPDATE public.produtos p
     SET categoria_id    = c.id,
         subcategoria_id = s.id,
         categoria       = c.nome
    FROM public.categorias_produto velha,
         public.categorias_produto c
    JOIN public.subcategorias_produto s ON s.categoria_id = c.id AND s.padrao AND s.nome = 'Câmeras digitais'
   WHERE p.categoria_id = velha.id
     AND velha.filial = 'TechMax' AND NOT velha.padrao
     AND public.nome_item_normalizado(velha.nome) = 'foto e video'
     AND public.nome_item_normalizado(p.nome) LIKE 'camera%'
     AND c.filial = 'TechMax' AND c.padrao AND c.nome = 'Câmeras e segurança';
END;
$m$;
